### PR TITLE
Dev core inputreader priorization

### LINKED ISSUE #1208: CobiGen InputReader can only catch InputReaderExceptions
### Expected behavior
As an Eclipse CobiGen Generate user, I want CobiGen to iterate over each InputReader and in case of an Exception in a single plugin continue the Generate process with another plugin.

### Actual behavior
If an InputReader plugin implementation throws a different Exception than InputReaderException while reading an inputfile, Eclipse shows an Error dialog and cancels the whole Generate process.

### PR DESCRIPTION
**Pull request by jan-vcapgemini**
Adresses #1209/Fixes #1208.

Implements

* Adds support for InputReader priorization
* fixes an issue with non catched Exceptions

@devonfw/cobigen

### CODE REVIEW

File: cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java [hunk 1]
```diff
@@ -43,4 +43,43 @@ public GenerationReportToAssert isSuccessful() {
...
+     * Checks if an Exception of the given class was NOT found in the {@link GenerationReportTo} error
+     * reports. errors.
+     *
+     * @param exception
+     *            Class of Exception to check for
+     * @return boolean
+     * @throws AssertionError
+     *             if the Exception was found in the report
+     */
+    public boolean notContainsException(Class exception) throws AssertionError {
```
Comment (maybeec) [inline cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java:77]: please return GenerationReportToAssert always to maintain builder pattern.

File: cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java [hunk 2]
```diff
@@ -43,4 +43,43 @@ public GenerationReportToAssert isSuccessful() {
...
+     */
+    public GenerationReportToAssert containsException(Class exception) throws AssertionError {
+
+        for (Throwable error : actual.getErrors()) {
+            if (error.getClass().equals(exception)) {
+                return this;
+            }
+        }
+        throw new AssertionError(
+            "Expected an Exception of class: " + exception + " in error reports but got something else.");
```
Comment (maybeec) [inline cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java:64]: Please also put out what you have seen. AssertJ error messages have the advantage over JUnit as they provide proper debugging information like messages as
`"Expected an exception of class "+ exception +", which could not be found in the list "+ actual.getErrors()`

btw. could be that you have to print the getErrors() properly to string as I don't know the type returned by heard.

File: cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java [hunk 3]
```diff
@@ -43,4 +43,43 @@ public GenerationReportToAssert isSuccessful() {
...
+    /**
+     * Checks if an Exception of the given class was found in the {@link GenerationReportTo} error reports.
+     *
+     * @param exception
+     *            Class of Exception to check for
+     * @return {@link GenerationReportToAssert}
+     * @throws AssertionError
+     *             if another or no Exception was found in the report
+     */
+    public GenerationReportToAssert containsException(Class exception) throws AssertionError {
```
Comment (maybeec) [inline cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java:56]: I think `Class` will give a compiler warning, please make it `Class<? extends Throwable>`

File: cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java (hunk 1 above)
Comment (maybeec) [reply cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java:77]: same here regarding Class parameter type

File: cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java [hunk 4]
```diff
@@ -68,23 +69,53 @@ public Object read(String type, Path path, Charset inputCharset, Object... addit
     public Object read(Path path, Charset inputCharset, Object... additionalArguments) throws InputReaderException {
         Set<String> keySet = PluginRegistry.getTriggerInterpreterKeySet();
         // We first try to find an input reader that is most likely readable
+        HashMap<String, Boolean> readableCache = new HashMap<String, Boolean>();
```
Comment (maybeec) [inline cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java:72]: Please declare maps always as `Map` interface, just the instance could be of `HashMap`

File: cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java [hunk 5]
```diff
@@ -68,23 +69,53 @@ public Object read(String type, Path path, Charset inputCharset, Object... addit
...
+            } catch (InputReaderException e) {
+                LOG.debug(
+                    "Was not able to read input {} with EXTERNAL inputreader '{}' although it was reported to be most likely readable. Trying next input reader...",
+                    path, s, e);
+            } catch (Throwable e) {
+                LOG.debug(
+                    "While reading the input {} with the EXTERNAL inputreader {}, an Exception occured. Trying next input reader...",
+                    path, s, e);
+            }
+        }
```
Comment (maybeec) [inline cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java:95]: this and the below is the exact same code. I would like to externalize it to a common method, which takes two parameters: the readableCache and the value to compare to for activation (e.g. true or null).

It would be also better, if you don't query all isMostLikelyReadable in advance to you have them cached. You should build up the cache as soon as you need to query a new plugin. This will increase performance tremendously as you might in a best case just query one plugin at all.

File: cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java (hunk 1 above)
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java]: adjusted.

File: cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java (hunk 2 above)
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java]: adjusted.

File: cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java (hunk 3 above)
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-parent/cobigen-core-test/src/main/java/com/devonfw/cobigen/test/assertj/GenerationReportToAssert.java]: adjusted.

File: cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java (hunk 4 above)
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java]: adjusted.

File: cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java (hunk 5 above)
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java:91]: Moved redundant code into new method.

File: cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java [hunk 6]
```diff
@@ -68,23 +70,79 @@ public Object read(String type, Path path, Charset inputCharset, Object... addit
...
+        // Create cache for readable states
         for (String s : keySet) {
-            try {
-                if (isMostLikelyReadable(s, path)) {
-                    LOG.debug("Try reading input {} with inputreader '{}'...", path, s);
+            readable = getValidInputReader(path, inputCharset, readableCache, s, additionalArguments);
+            if (readable != null) {
+                return readable;
+            }
+            readableCache.put(s, isMostLikelyReadable(s, path));
```
Comment (maybeec) [inline cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java:82]: you called now isMostLikelyReadable three times each iteration :)

File: cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java [hunk 7]
```diff
@@ -68,23 +70,79 @@ public Object read(String type, Path path, Charset inputCharset, Object... addit
     public Object read(Path path, Charset inputCharset, Object... additionalArguments) throws InputReaderException {
         Set<String> keySet = PluginRegistry.getTriggerInterpreterKeySet();
```
[the remark this answers is not in the document]
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java]: adjusted.

File: cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java (hunk 6 above)
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java]: adjusted.

File: cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java [hunk 8]
```diff
@@ -68,23 +70,79 @@ public Object read(String type, Path path, Charset inputCharset, Object... addit
...
+     *            of the input to be used
+     * @param readableCache
+     *            HashMap of TriggerInterpreter and Boolean
+     * @param s
+     *            TriggerInterpreter
+     * @param additionalArguments
+     *            depending on the InputReader implementation
+     * @return Object that is a valid input or null if the file cannot be read by any InputReader
+     */
+    private Object getValidInputReader(Path path, Charset inputCharset, Map<String, Boolean> readableCache, String s,
```
[the remark this answers is not in the document]
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java]: adjusted the name.

File: cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java [hunk 9]
```diff
@@ -68,23 +70,79 @@ public Object read(String type, Path path, Charset inputCharset, Object... addit
...
+        Object... additionalArguments) {
+        String readerType = "EXTERNAL";
+        try {
+            if (isMostLikelyReadable(s, path) != null && isMostLikelyReadable(s, path)) {
+                LOG.info("Try reading input {} with {} inputreader '{}'...", path, readerType, s);
+                return getInputReader(s).read(path, inputCharset, additionalArguments);
+            }
```
[the remark this answers is not in the document]
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java]: fixed.

File: cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java [hunk 10]
```diff
@@ -68,23 +70,79 @@ public Object read(String type, Path path, Charset inputCharset, Object... addit
...
+     * @param inputCharset
+     *            of the input to be used
+     * @param readableCache
+     *            HashMap of TriggerInterpreter and Boolean
+     * @param s
+     *            TriggerInterpreter
+     * @param additionalArguments
+     *            depending on the InputReader implementation
+     * @return Object that is a valid input or null if the file cannot be read by any InputReader
+     */
```
[the remark this answers is not in the document]
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/InputInterpreterImpl.java:112]: not sure what I should change here.

**Review by maybeec — APPROVED** [review]
