### PR TITLE
1495 fixed working branch adapt templates feature

### LINKED ISSUE #1642: Adapt Template Sets Process
As a cobigen user, I want so to be able to adapt template sets into my workspace. 
Use old pull request #1631.

- [ ] Refactor functionality "get jars to adapt" from CLI to core-api, so GUI can use it
- [ ] If the user adapts template sets from eclipse we should import the folder
- [ ] Prepare Tests for SWTBot

Further Questions:
- Should it be possible to adapt single template sets through Template Set Management GUI?
- Should GUI load full config?
- Import as Maven Project and define in POM or File System Folder?

### PR DESCRIPTION
**Pull request by quantumfate**
Adresses/Fixes #1642 and #1595 .

Implements

* MavenCoordinatePair data structure to transport relevant information about TemplateSets
* The CLI fetches information based on user input

@devonfw/cobigen

### CODE REVIEW

File: cobigen-cli/cli-systemtest/src/test/java/com/devonfw/cobigen/cli/systemtest/AdaptTemplatesCommandIT.java [hunk 1]
```diff
@@ -54,13 +66,29 @@ public void adaptTemplateSetTest() throws Exception {
     assertThat(downloadedTemplateSetsFolderPath).exists();
     assertThat(adaptedTemplateSetsFolderPath).exists();
 
+    Path templateSet = adaptedTemplateSetsFolderPath.resolve("crud-java-server-app-2021.12.007");
```
Comment (jan-vcapgemini) [inline cobigen-cli/cli-systemtest/src/test/java/com/devonfw/cobigen/cli/systemtest/AdaptTemplatesCommandIT.java:68]: Better make this version dynamic.

File: cobigen/cobigen-core-systemtest/src/test/java/com/devonfw/cobigen/systemtest/TemplateProcessingTest.java [hunk 2]
```diff
@@ -69,30 +77,228 @@ public void prepare() throws IOException {
...
+        TemplateProcessingTest.class.getProtectionDomain().getCodeSource().getLocation().toURI()).getParentFile()
+            .getParentFile().getParentFile().getParentFile().toPath().resolve("cobigen-templates")
+            .resolve("crud-java-server-app").resolve("target");
+    File jars = devTemplateSetPath.toFile();
+    List<String> filenames = new ArrayList<>(2);
+    for (File file : jars.listFiles()) {
+      if (file.getName().endsWith(".jar")) {
+        filenames.add(file.getName());
+      }
+    }
```
Comment (jan-vcapgemini) [inline cobigen/cobigen-core-systemtest/src/test/java/com/devonfw/cobigen/systemtest/TemplateProcessingTest.java:95]: This needs to be replaced with a static / reduced template set.

File: cobigen/cobigen-core-systemtest/src/test/java/com/devonfw/cobigen/systemtest/TemplateProcessingTest.java [hunk 3]
```diff
@@ -69,30 +77,228 @@ public void prepare() throws IOException {
...
+            .getParentFile().getParentFile().getParentFile().toPath().resolve("cobigen-templates")
+            .resolve("crud-java-server-app").resolve("target");
+    Path devTemplateSetPath2 = new File(
+        TemplateProcessingTest.class.getProtectionDomain().getCodeSource().getLocation().toURI()).getParentFile()
+            .getParentFile().getParentFile().getParentFile().toPath().resolve("cobigen-templates")
+            .resolve("crud-java-server-app-complex").resolve("target");
+    Path devTemplateSetPath3 = new File(
+        TemplateProcessingTest.class.getProtectionDomain().getCodeSource().getLocation().toURI()).getParentFile()
+            .getParentFile().getParentFile().getParentFile().toPath().resolve("cobigen-templates")
+            .resolve("crud-openapi-java-server-app").resolve("target");
```
Comment (jan-vcapgemini) [inline cobigen/cobigen-core-systemtest/src/test/java/com/devonfw/cobigen/systemtest/TemplateProcessingTest.java:187]: This needs to be replaced with a static / reduced template set.

File: cobigen/cobigen-core-api/src/main/java/com/devonfw/cobigen/api/util/mavencoordinate/MavenCoordinate.java [hunk 4]
```diff
@@ -0,0 +1,185 @@
...
+
+    //@formatter:off
+    /**
+     * Pattern to match artifact id and versions for template set jars:
+     * Group 1: artifact id
+     * Group 2: version
+     * Group 3: snapshot or latest
+     */
+    //@formatter:on
+    public static final String MAVEN_COORDINATE_JAR_PATTERN = "([a-zA-Z-]+)-([\\d.]+)(-SNAPSHOT|-LATEST)?\\.jar";
```
Comment (jan-vcapgemini) [inline cobigen/cobigen-core-api/src/main/java/com/devonfw/cobigen/api/util/mavencoordinate/MavenCoordinate.java:40]: Move inner class into separate class.

File: cobigen/cobigen-core-api/src/main/java/com/devonfw/cobigen/api/util/mavencoordinate/MavenCoordinate.java [hunk 5]
```diff
@@ -0,0 +1,185 @@
...
+
+    /**
+     * Used to denote the first regex group index of the artifactId
+     */
+    public static final int ARTIFACT_ID_REGEX_GROUP = 1;
+
+    /**
+     * Used to denote the second regex group index of the version
+     */
+    public static final int VERSION_REGEX_GROUP = 2;
```
Comment (jan-vcapgemini) [inline cobigen/cobigen-core-api/src/main/java/com/devonfw/cobigen/api/util/mavencoordinate/MavenCoordinate.java:30]: Move to constants class and add better description.

**Review by jan-vcapgemini — APPROVED** [review]

File: cobigen/cobigen-core-systemtest/src/test/java/com/devonfw/cobigen/systemtest/TemplateProcessingTest.java (hunk 3 above)
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-systemtest/src/test/java/com/devonfw/cobigen/systemtest/TemplateProcessingTest.java]: done

File: cobigen/cobigen-core-systemtest/src/test/java/com/devonfw/cobigen/systemtest/TemplateProcessingTest.java (hunk 2 above)
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-systemtest/src/test/java/com/devonfw/cobigen/systemtest/TemplateProcessingTest.java]: done

File: cobigen-cli/cli-systemtest/src/test/java/com/devonfw/cobigen/cli/systemtest/AdaptTemplatesCommandIT.java (hunk 1 above)
Comment (jan-vcapgemini) [reply cobigen-cli/cli-systemtest/src/test/java/com/devonfw/cobigen/cli/systemtest/AdaptTemplatesCommandIT.java]: not needed anymore.

File: cobigen/cobigen-core-api/src/main/java/com/devonfw/cobigen/api/util/mavencoordinate/MavenCoordinate.java (hunk 4 above)
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-api/src/main/java/com/devonfw/cobigen/api/util/mavencoordinate/MavenCoordinate.java]: not needed anymore.

File: cobigen/cobigen-core-api/src/main/java/com/devonfw/cobigen/api/util/mavencoordinate/MavenCoordinate.java (hunk 5 above)
Comment (jan-vcapgemini) [reply cobigen/cobigen-core-api/src/main/java/com/devonfw/cobigen/api/util/mavencoordinate/MavenCoordinate.java]: not needed anymore.
