### PR TITLE
make the update bar show Progress and make the generation cancelable

### LINKED ISSUE #867: Cobigen processbar
### Expected behavior
When i use cobigen to generate code i want to see how long it takes until it is finished and i want the option to cancel the code generation (maybe if it takes too long). 

### Actual behavior
At the moment we have a processbar but it is not working as expected. Wenn i generate some code there is nothing happen and you can't use the cancel button its disabled. Not before the generation is nearly allready finished there appear a few more windows and then the generation is finished. Especially if i generate a lage amount of code, i have to wait a long time and don't know if it is still working or if eclipse suspended completly.

grafik

### PR DESCRIPTION
**Pull request by LarsReinken**
Adresses/Fixes #867.

Implements

* 
* 
* 

@devonfw/cobigen

### CODE REVIEW

File: cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/GenerationProcessorImpl.java [hunk 1]
```diff
@@ -143,29 +149,36 @@ public GenerationReportTo generate(Object input, List<? extends GenerableArtifac
...
+        } catch (CobiGenRuntimeException e) {
+            generationReport.setTemporaryWorkingDirectory(tmpTargetRootPath);
+            generationReport.addError(e);
+            LOG.error("An internal error occurred during generation.", e);
+        } catch (Throwable e) {
+            generationReport.setTemporaryWorkingDirectory(tmpTargetRootPath);
+            generationReport.addError(new CobiGenRuntimeException(
+                "Something unexpected happened" + ((e.getMessage() != null) ? ": " + e.getMessage() : "!"), e));
+            LOG.error("An unknown exception occurred during generation.", e);
         }
```
Comment (maybeec) [inline cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/generator/GenerationProcessorImpl.java]: Please keep the existing logic and abort anyhow by building another try catch around
